repos:
- repo: local
  hooks:
  - id: rust-clippy
    name: Rust Clippy
    entry: cargo clippy
    language: system
    types: [rust]
  - id: rust-fmt
    name: Rust Format
    entry: cargo fmt -- --check
    language: system
    types: [rust]