[package]
name = "peg"
version = "0.0.1"
edition = "2021"
build = "build.rs"

[dependencies]
convert_case = "0.6.0"
dialoguer = "0.11.0"
lazy_static = "1.5.0"
regex = "1.11.1"
serde = "1.0.213"
tera = "1.20.0"
validator = { version = "0.18.1", features = ["derive"] }
validator_derive = "0.18.2"
