name: Release

on:
  release:
    types: 
      - published
      - prereleased
      - edited

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - name: Add targets
        run: |
          rustup target add x86_64-unknown-linux-gnu

      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build binaries
        run: |
          cargo build --target x86_64-unknown-linux-musl --release

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/x86_64-unknown-linux-musl/release/peg
          asset_name: linux-binary
          asset_content_type: application/octet-stream
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}